### ISSUE TITLE
Allow callers of createPromoPlanet to specify the genome

### ISSUE THREAD

**Issue by austinatchley** [Earthereum/eth-space-mining#12]
Right now, the parameter only describes a seed that is hashed with the block number to provide the genetic code for the new planet. The caller should be allowed to specify the exact genome in createPromoPlanet. Maybe another method called createRandomPromoPlanet should be created implementing the previous behavior described above.

**Comment by loganzartman** [comment]
Fixed in 8f6100231145e41d0a1929d2c3d404912310f82f
